const AUTHSTATE = {
    LOGIN_USER: "LOGIN_USER",
    REGISTER_USER: "REGISTER_USER",
    LOGIN_MENTOR: "LOGIN_MENTOR",
    REGISTER_MENTOR: "REGISTER_MENTOR",
    LOGIN_ADMIN: "LOGIN_ADMIN"
}

export default AUTHSTATE;